import { ObjectValues } from './common'
import {RARITY_ALIAS, RARITY_VALUES} from "../filters/rarity";
import {NEW_VALUES} from "../filters/new";
import {PREFER_VALUES} from "../filters/print";
import {FORMATS} from "../filters/format";
import {IS_VALUES} from "./card";
import {SORT_ORDERS} from "../filters/order";
import {LANGUAGE_ALIASES, LANGUAGES} from "../filters/language";

export const FILTER_KEYWORDS = {
  '!': '!',
  a: 'a', artist: 'artist',
  banned: 'banned',
  border: 'border',
  c: 'c', color: 'color',
  cn: 'cn', number: 'number',
  ci: 'ci', commander: 'commander', id: 'id', identity: 'identity',
  cmc: 'cmc', mv: 'mv', manavalue: 'manavalue',
  // list and ctag are custom aliases for cube
  cube: 'cube', list: 'list', ctag: 'ctag',
  date: 'date', year: 'year',
  devotion: 'devotion', // !Devotion can only match single color or hybrid mana. No two-brid either
  direction: 'direction', dir: 'dir',
  e: 'e', edition: 'edition', s: 's', set: 'set',
  eur: 'eur',
  f: 'f', format: 'format',
  fo: 'fo',
  frame: 'frame',
  flavor: 'flavor', ft: 'ft',
  game: 'game',
  is: 'is', has: 'has',
  in: 'in',
  keyword: 'keyword', kw: 'kw',
  keywords: 'keywords',
  lang: 'lang', language: 'language',
  layout: 'layout',
  loy: 'loy', loyalty: 'loyalty',
  m: 'm', mana: 'mana',
  name: 'name',
  not: 'not',
  o: 'o', oracle: 'oracle',
  pow: 'pow', power: 'power',
  def: 'def', defense: 'defense',
  powtou: 'powtou', pt: 'pt',
  produces: 'produces',
  prints: 'prints',
  order: 'order',
  r: 'r', rarity: 'rarity',
  restricted: 'restricted',
  st: 'st', settype: 'settype',
  lore: "lore",
  stamp: 'stamp',
  t: 't', type: 'type',
  text: 'text',
  tix: 'tix',
  tou: 'tou', toughness: 'toughness',
  usd: 'usd',
  unique: 'unique',
  watermark: 'watermark', wm: 'wm',
  // Requires tagging data
  function: 'function', oracletag: 'oracletag', otag: 'otag',
  art: 'art', arttag: 'arttag', atag: 'atag',
  // https://discord.com/channels/291498816459243521/361685936179904513/1104796430830411777
  new: 'new', // rarity, flavor, art, artist, frame, language, game, paper, mtgo, arena, nonfoil, foil
  // its not: etched, masterpiece, promo, border, stamp
  prefer: 'prefer',
  // Requires set data
  b: 'b', block: 'block',
  paperprints: 'paperprints',
  papersets: 'papersets',
  sets: 'sets',
  scryfallid: "scryfallid",
  oracleid: "oracleid",
  // mtgql exclusive
  collection: "collection",
  lim: "lim", limit: "limit",
  ogo: "ogo", ogtext: "ogtext",
  fogo: "fogo", fogtext: "fogtext",
  ogt: "ogt", ogtype: "ogtype",
  pips: "pips",
} as const

export const KEYWORDS_TO_IMPLEMENT = {
  // these affect scryfall's UI behavior. are they needed here?
  // include: 'include', // maybe this one overrides a similar scryfall default?
  // display: 'display', is display needed?
} as const

const all = {
  ...FILTER_KEYWORDS,
  ...KEYWORDS_TO_IMPLEMENT,
} as const

export type FilterKeyword = ObjectValues<typeof all>

export enum FilterType {
  CmcInt,
  CmcOddEven,
  Name,
  NameFuzzy,
  NameExact,
  NameRegex,
  ColorSet,
  ColorInt,
  ColorIdentitySet,
  ColorIdentityInt,
  Mana,
  ManaRegex,
  Oracle,
  OracleRegex,
  OracleCount,
  FullOracle,
  FullOracleRegex,
  FullOracleCount,
  OriginalText,
  OriginalTextRegex,
  OriginalTextCount,
  FullOriginalText,
  FullOriginalTextRegex,
  FullOriginalTextCount,
  Keyword,
  KeywordCount,
  Type,
  TypeRegex,
  OriginalType,
  OriginalTypeRegex,
  Power,
  Tough,
  PowTou,
  Loyalty,
  Defense,
  Layout,
  Format,
  Banned,
  Restricted,
  Is,
  Not,
  Prints,
  PaperPrints,
  Sets,
  PaperSets,
  In,
  ProducesSet,
  ProducesInt,
  Devotion,
  Unique,
  Order,
  Direction,
  Rarity,
  Set,
  SetType,
  Artist,
  CollectorNumber,
  Border,
  Date,
  Price,
  Frame,
  Flavor,
  FlavorRegex,
  FlavorCount,
  Game,
  Language,
  Stamp,
  Watermark,
  CubeOracle,
  CubePrints,
  OracleTag,
  IllustrationTag,
  New,
  Prefer,
  Block,
  Collection,
  ScryfallId,
  OracleId,
  Identity,
  Limit,
  Lore,
  Pips
}

interface FilterTypeRepr {
  name: string
  validValues: string[]
  aliasValues?: { [key: string]: string }
}

export const FILTERTYPE_REPR: Record<FilterType, FilterTypeRepr> = {
  // Fill in valid values as we need them. not all filter types need them
  [FilterType.CmcInt]: { name: "cmc", validValues: [] },
  [FilterType.CmcOddEven]: { name: "cmc", validValues: [] },
  [FilterType.Name]: { name: "name", validValues: [] },
  [FilterType.NameFuzzy]: { name: "fuzzy name", validValues: [] },
  [FilterType.NameExact]: { name: "name", validValues: [] },
  [FilterType.NameRegex]: { name: "name", validValues: [] },
  [FilterType.ColorSet]: { name: "color", validValues: [] },
  [FilterType.ColorInt]: { name: "color", validValues: [] },
  [FilterType.ColorIdentitySet]: { name: "color identity", validValues: [] },
  [FilterType.ColorIdentityInt]: { name: "color identity", validValues: [] },
  [FilterType.Mana]: { name: "mana", validValues: [] },
  [FilterType.ManaRegex]: { name: "mana", validValues: [] },
  [FilterType.Oracle]: { name: "oracle text", validValues: [] },
  [FilterType.OracleRegex]: { name: "oracle regex", validValues: [] },
  [FilterType.OracleCount]: { name: "oracle count", validValues: [] },
  [FilterType.FullOracle]: { name: "full oracle text", validValues: [] },
  [FilterType.FullOracleRegex]: { name: "full oracle text", validValues: [] },
  [FilterType.FullOracleCount]: { name: "full oracle text", validValues: [] },
  [FilterType.OriginalText]: { name: "original text", validValues: [] },
  [FilterType.OriginalTextRegex]: { name: "original text regex", validValues: [] },
  [FilterType.OriginalTextCount]: { name: "original text count", validValues: [] },
  [FilterType.FullOriginalText]: { name: "full original text", validValues: [] },
  [FilterType.FullOriginalTextRegex]: { name: "full original text regex", validValues: [] },
  [FilterType.FullOriginalTextCount]: { name: "full original text count", validValues: [] },
  [FilterType.Keyword]: { name: "keyword", validValues: [] },
  [FilterType.KeywordCount]: { name: "keyword", validValues: [] },
  [FilterType.Type]: { name: "type", validValues: [] },
  [FilterType.TypeRegex]: { name: "type regex", validValues: [] },
  [FilterType.OriginalType]: { name: "original type", validValues: [] },
  [FilterType.OriginalTypeRegex]: { name: "original type regex", validValues: [] },
  [FilterType.Power]: { name: "power", validValues: [] },
  [FilterType.Tough]: { name: "toughness", validValues: [] },
  [FilterType.PowTou]: { name: "combined power and toughness", validValues: [] },
  [FilterType.Loyalty]: { name: "loyalty", validValues: [] },
  [FilterType.Defense]: { name: "defense", validValues: [] },
  [FilterType.Layout]: { name: "layout", validValues: [] },
  [FilterType.Format]: { name: "format", validValues: FORMATS },
  [FilterType.Banned]: { name: "banned", validValues: FORMATS },
  [FilterType.Restricted]: { name: "restricted", validValues: FORMATS },
  [FilterType.Is]: { name: "is", validValues: IS_VALUES },
  [FilterType.Not]: { name: "not", validValues: IS_VALUES },
  [FilterType.Prints]: { name: "print count", validValues: [] },
  [FilterType.PaperPrints]: { name: "paper print count", validValues: [] },
  [FilterType.Sets]: { name: "set count", validValues: [] },
  [FilterType.PaperSets]: { name: "paper set count", validValues: [] },
  [FilterType.In]: { name: "in", validValues: [] },
  [FilterType.ProducesSet]: { name: "produces", validValues: [] },
  [FilterType.ProducesInt]: { name: "produces", validValues: [] },
  [FilterType.Devotion]: { name: "devotion", validValues: [] },
  [FilterType.Unique]: { name: "unique", validValues: [] },
  [FilterType.Order]: { name: "order", validValues: Object.keys(SORT_ORDERS) },
  [FilterType.Direction]: { name: "direction", validValues: [] },
  [FilterType.Rarity]: { name: "rarity", validValues: RARITY_VALUES, aliasValues: RARITY_ALIAS },
  [FilterType.Set]: { name: "set", validValues: [] },
  [FilterType.SetType]: { name: "set type", validValues: [] },
  [FilterType.Artist]: { name: "artist", validValues: [] },
  [FilterType.CollectorNumber]: { name: "collector number", validValues: [] },
  [FilterType.Border]: { name: "border", validValues: [] },
  [FilterType.Date]: { name: "date", validValues: [] },
  [FilterType.Price]: { name: "price", validValues: [] },
  [FilterType.Frame]: { name: "frame", validValues: [] },
  [FilterType.Flavor]: { name: "flavor text", validValues: [] },
  [FilterType.FlavorRegex]: { name: "flavor text", validValues: [] },
  [FilterType.FlavorCount]: { name: "flavor text", validValues: [] },
  [FilterType.Game]: { name: "game", validValues: [] },
  [FilterType.Language]: { name: "language", validValues: LANGUAGES, aliasValues: LANGUAGE_ALIASES },
  [FilterType.Stamp]: { name: "stamp", validValues: [] },
  [FilterType.Watermark]: { name: "watermark", validValues: [] },
  [FilterType.CubeOracle]: { name: "cube cards", validValues: [] },
  [FilterType.CubePrints]: { name: "cube prints", validValues: [] },
  [FilterType.OracleTag]: { name: "oracle tag", validValues: [] },
  [FilterType.IllustrationTag]: { name: "illustration tag", validValues: [] },
  [FilterType.New]: { name: "new", validValues: NEW_VALUES },
  [FilterType.Prefer]: { name: "prefer", validValues: PREFER_VALUES },
  [FilterType.Block]: { name: "block", validValues: [] },
  [FilterType.Collection]: { name: "collection", validValues: [] },
  [FilterType.ScryfallId]: { name: "scryfall-id", validValues: [] },
  [FilterType.OracleId]: { name: "oracle-id", validValues: [] },
  [FilterType.Identity]: { name: "all", validValues: [] },
  [FilterType.Limit]: { name: "limit", validValues: [] },
  [FilterType.Lore]: { name: "lore", validValues: [] },
  [FilterType.Pips]: { name: "pips", validValues: [] },
}