import {Card} from "../../generated";

export const collectThemAll: Card = {
    "object": "card",
    "oracle_id": "ca3cc7c1-ca4f-4d49-9b1b-2942f289862d",
    "name": "1997 World Championships Ad",
    "layout": "token",
    "mana_cost": "",
    "cmc": 0,
    "type_line": "Card",
    "oracle_text": "",
    "colors": [],
    "color_identity": [],
    "keywords": [],
    "legalities": {
        "standard": "not_legal",
        "future": "not_legal",
        "historic": "not_legal",
        "timeless": "not_legal",
        "gladiator": "not_legal",
        "pioneer": "not_legal",
        "explorer": "not_legal",
        "modern": "not_legal",
        "legacy": "not_legal",
        "pauper": "not_legal",
        "vintage": "not_legal",
        "penny": "not_legal",
        "commander": "not_legal",
        "oathbreaker": "not_legal",
        "standardbrawl": "not_legal",
        "brawl": "not_legal",
        "alchemy": "not_legal",
        "paupercommander": "not_legal",
        "duel": "not_legal",
        "oldschool": "not_legal",
        "premodern": "not_legal",
        "predh": "not_legal"
    },
    "reserved": false,
    "foil": false,
    "nonfoil": true,
    "purchase_uris": {
        "tcgplayer": "https://tcgplayer.pxf.io/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3D1997%2BWorld%2BChampionships%2BAd%26view%3Dgrid",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=1997+World+Championships+Ad&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=1997+World+Championships+Ad&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
    },
    "card_faces": [],
    "artist": "",
    "booster": false,
    "border_color": "gold",
    "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    "collector_number": "0",
    "digital": false,
    "finishes": [
        "nonfoil"
    ],
    "frame": "1997",
    "games": [
        "paper"
    ],
    "highres_image": true,
    "id": "40b9dcb9-05c1-4a2e-b0cb-6554483ca5c9",
    "image_status": "highres_scan",
    "image_uris": {
        "small": "https://cards.scryfall.io/small/front/4/0/40b9dcb9-05c1-4a2e-b0cb-6554483ca5c9.jpg?1562908403",
        "normal": "https://cards.scryfall.io/normal/front/4/0/40b9dcb9-05c1-4a2e-b0cb-6554483ca5c9.jpg?1562908403",
        "large": "https://cards.scryfall.io/large/front/4/0/40b9dcb9-05c1-4a2e-b0cb-6554483ca5c9.jpg?1562908403",
        "png": "https://cards.scryfall.io/png/front/4/0/40b9dcb9-05c1-4a2e-b0cb-6554483ca5c9.png?1562908403",
        "art_crop": "https://cards.scryfall.io/art_crop/front/4/0/40b9dcb9-05c1-4a2e-b0cb-6554483ca5c9.jpg?1562908403",
        "border_crop": "https://cards.scryfall.io/border_crop/front/4/0/40b9dcb9-05c1-4a2e-b0cb-6554483ca5c9.jpg?1562908403"
    },
    "lang": "en",
    "multiverse_ids": [],
    "prices": {
        "usd": null,
        "usd_foil": null,
        "usd_etched": null,
        "eur": null,
        "eur_foil": null,
        "tix": null
    },
    "promo": false,
    "rarity": "common",
    "released_at": "1997-08-13",
    "reprint": false,
    "scryfall_uri": "https://scryfall.com/card/wc97/0/1997-world-championships-ad?utm_source=api",
    "set": "wc97",
    "set_id": "8b791ead-c9b5-42fa-9ffb-43f178af5ac8",
    "set_name": "World Championship Decks 1997",
    "set_type": "memorabilia",
    "oversized": false,
    "variation": false,
    "full_art": false,
    "textless": false,
    "story_spotlight": false
} as Card;